name: Build candido-middleware

on:
  pull_request:
    paths:
      - 'candido-middleware/**'
      - '.github/workflows/pull_request_github_action.yml'

jobs:
  build:
    name: Build candido-middleware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.15

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
